### ISSUE TITLE
您好，请问您的论文接收没有啊？

### ISSUE THREAD

**Issue by dugzzuli** [cshaowang/gmc#1]
您好，请问您的接收没有啊？在哪里可以下载到您的论文啊？

**Comment by cshaowang** [comment]
您好！非常感谢您的关注。这个工作仍在审稿中。发布在这里的代码是为了辅助审稿人审核我们的工作。录用后，我会及时更新详细的信息。谢谢！

**Comment by dugzzuli** [comment]
师兄好。我是杜国王，在云南大学读书，就是想问一下，您的这个数据集是怎么构造的啊？ 看了好几篇论文这个数据构造都没有说清楚，发了好几封邮件，只有您给我回了一下  非常谢谢师兄

**Comment by cshaowang** [comment]
有几篇综述文章，供参考：
A Survey on Multi-view Learning. arXiv preprint, 2013.
Multi-view clustering: A survey. Big Data Mining and Analytics, 2018.
...

**Comment by dugzzuli** [comment]
好的 收到 谢谢师兄 😄
